import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}


        <script
          type="module"
          src="node_modules/@material-tailwind/html@latest/scripts/popover.js"
        ></script>


        <script
          type="module"
          src="https://unpkg.com/@material-tailwind/html@latest/scripts/popover.js"
        ></script>
      </body>

    </html>
  );
}
